package com.example.downloader.engine

import com.example.domain.model.DownloadError
import java.io.File
import java.util.regex.Pattern

/**
 * Deterministic detector for yt-dlp download outputs.
 *
 * Guarantees that:
 * 1. Output files are selected strictly based on predictable task template and logged destinations.
 * 2. Intermediate fragments (.f137, .temp), part files (.part, .ytdl), subtitles (.vtt, .srt),
 *    thumbnails (.jpg, .webp), and metadata (.info.json) are strictly excluded.
 * 3. File size (maxByOrNull { it.length() }) is NEVER used to select the final artifact.
 * 4. If the output cannot be reliably identified, a clear DownloadError is returned instead of guessing.
 */
object OutputFileDetector {

    private val EXCLUDED_EXTENSIONS = setOf(
        // Part & temp files
        "part", "ytdl", "temp", "tmp", "crdownload",
        // Subtitle files
        "vtt", "srt", "lrc", "ass", "ssa", "sub", "sbv", "ttml", "dfxp",
        // Thumbnail & image files
        "jpg", "jpeg", "png", "webp", "gif", "bmp", "ico",
        // Metadata & log files
        "json", "info", "description", "dump", "xml", "log", "txt"
    )

    private val VALID_AUDIO_EXTENSIONS = setOf(
        "mp3", "m4a", "opus", "ogg", "flac", "wav", "aac"
    )

    private val VALID_VIDEO_EXTENSIONS = setOf(
        "mp4", "mkv", "webm", "3gp", "flv", "avi", "mov"
    )

    // Regex matching intermediate format fragments generated by yt-dlp (e.g. task_123.f137.mp4)
    private val FRAGMENT_PATTERN = Pattern.compile("""\.f\d+(\.|$)""", Pattern.CASE_INSENSITIVE)

    // Regex matching subtitle language patterns (e.g. task_123.ar.vtt, task_123.en-US.srt)
    private val SUBTITLE_LANG_PATTERN = Pattern.compile("""\.[a-z]{2,3}(?:-[a-zA-Z0-9]+)?\.(?:vtt|srt|ass|lrc)""", Pattern.CASE_INSENSITIVE)

    // Patterns to capture exact destination files logged by yt-dlp stdout
    private val MERGER_PATTERN = Pattern.compile("""\[Merger\]\s+Merging formats into\s+["']?([^"'\r\n]+)["']?""")
    private val EXTRACT_AUDIO_PATTERN = Pattern.compile("""\[ExtractAudio\]\s+Destination:\s+["']?([^"'\r\n]+)["']?""")
    private val DOWNLOAD_DEST_PATTERN = Pattern.compile("""\[download\]\s+Destination:\s+["']?([^"'\r\n]+)["']?""")
    private val ALREADY_DOWNLOADED_PATTERN = Pattern.compile("""\[download\]\s+["']?([^"'\r\n]+)["']?\s+has already been downloaded""")
    private val FIXUP_PATTERN = Pattern.compile("""\[Fixup[a-zA-Z0-9]+\]\s+Correcting container in\s+["']?([^"'\r\n]+)["']?""")

    /**
     * Extracts potential destination paths from a line of yt-dlp output.
     */
    fun extractDestinationFromLog(line: String): String? {
        val trimmed = line.trim()
        if (trimmed.isBlank()) return null

        val mergerMatcher = MERGER_PATTERN.matcher(trimmed)
        if (mergerMatcher.find()) return mergerMatcher.group(1)?.trim()

        val extractAudioMatcher = EXTRACT_AUDIO_PATTERN.matcher(trimmed)
        if (extractAudioMatcher.find()) return extractAudioMatcher.group(1)?.trim()

        val fixupMatcher = FIXUP_PATTERN.matcher(trimmed)
        if (fixupMatcher.find()) return fixupMatcher.group(1)?.trim()

        val alreadyMatcher = ALREADY_DOWNLOADED_PATTERN.matcher(trimmed)
        if (alreadyMatcher.find()) return alreadyMatcher.group(1)?.trim()

        val destMatcher = DOWNLOAD_DEST_PATTERN.matcher(trimmed)
        if (destMatcher.find()) {
            val candidate = destMatcher.group(1)?.trim().orEmpty()
            // Avoid intermediate fragment notifications
            if (!FRAGMENT_PATTERN.matcher(candidate).find()) {
                return candidate
            }
        }

        return null
    }

    /**
     * Returns true if the file is an intermediate fragment, partial, subtitle, thumbnail, or metadata.
     */
    fun isIntermediateOrExcluded(file: File, isAudioOnly: Boolean): Boolean {
        val name = file.name
        val ext = file.extension.lowercase()

        // 1. Explicitly excluded extension
        if (EXCLUDED_EXTENSIONS.contains(ext)) return true

        // 2. Part or temp marker
        if (name.endsWith(".part") || name.endsWith(".ytdl") || name.contains(".temp") || name.contains(".tmp")) {
            return true
        }

        // 3. Intermediate yt-dlp format stream fragment (e.g. .f137.mp4, .f140.m4a)
        if (FRAGMENT_PATTERN.matcher(name).find()) return true

        // 4. Subtitle naming pattern
        if (SUBTITLE_LANG_PATTERN.matcher(name).find()) return true

        // 5. Must have a valid media extension
        val validExtensions = if (isAudioOnly) {
            VALID_AUDIO_EXTENSIONS
        } else {
            VALID_VIDEO_EXTENSIONS + VALID_AUDIO_EXTENSIONS
        }

        if (!validExtensions.contains(ext)) return true

        // 6. Must not be empty
        if (file.length() <= 0L) return true

        return false
    }

    /**
     * Resolves the single true output file for a task deterministically without using file size.
     */
    fun resolveOutputFile(
        workDir: File,
        taskId: String,
        isAudioOnly: Boolean,
        loggedDestinations: Set<String> = emptySet(),
        taskPrefix: String = "task_$taskId"
    ): Result<File> {
        if (!workDir.exists() || !workDir.isDirectory) {
            return Result.failure(
                DownloadError.Generic(
                    msg = "Download finished, but task working directory was not found.",
                    detail = "Directory does not exist: ${workDir.absolutePath}"
                )
            )
        }

        // 1. Check logged destination paths first
        val loggedCandidates = loggedDestinations
            .map { File(it) }
            .filter { candidate ->
                candidate.exists() && candidate.isFile &&
                    !isIntermediateOrExcluded(candidate, isAudioOnly) &&
                    (candidate.parentFile?.absolutePath == workDir.absolutePath || candidate.name.startsWith(taskPrefix))
            }

        // If a logged candidate matches the cut file explicitly (Stage 3 after Merge)
        val cutLogged = loggedCandidates.firstOrNull { it.name.startsWith("${taskPrefix}_cut.") && it.length() > 0L }
        if (cutLogged != null) {
            return Result.success(cutLogged)
        }

        // If a logged candidate matches the merged file explicitly
        val mergedLogged = loggedCandidates.firstOrNull { it.name == "${taskPrefix}_merged.mp4" }
        if (mergedLogged != null && mergedLogged.length() > 0L) {
            return Result.success(mergedLogged)
        }

        if (loggedCandidates.size == 1) {
            return Result.success(loggedCandidates.first())
        }

        // 2. Inspect workDir for files matching the expected task output template
        val allFiles = workDir.listFiles()?.toList() ?: emptyList()
        val validCandidates = allFiles.filter { file ->
            file.isFile &&
                file.name.startsWith(taskPrefix) &&
                !isIntermediateOrExcluded(file, isAudioOnly)
        }

        // Check for explicit cut output first, then merged output
        val explicitCut = validCandidates.firstOrNull { it.name.startsWith("${taskPrefix}_cut.") && it.length() > 0L }
        if (explicitCut != null) {
            return Result.success(explicitCut)
        }

        // Check for explicit merged output
        val explicitMerged = validCandidates.firstOrNull { it.name == "${taskPrefix}_merged.mp4" }
        if (explicitMerged != null && explicitMerged.length() > 0L) {
            return Result.success(explicitMerged)
        }

        // If no candidates found
        if (validCandidates.isEmpty()) {
            return Result.failure(
                DownloadError.Generic(
                    msg = "Download finished, but output file was not found or is empty.",
                    detail = "No valid media output file matching '$taskPrefix' in ${workDir.absolutePath}."
                )
            )
        }

        // Exactly one valid candidate
        if (validCandidates.size == 1) {
            return Result.success(validCandidates.first())
        }

        // Filter by specific media type if multiple candidates remain
        val typeFiltered = if (isAudioOnly) {
            validCandidates.filter { VALID_AUDIO_EXTENSIONS.contains(it.extension.lowercase()) }
        } else {
            validCandidates.filter { VALID_VIDEO_EXTENSIONS.contains(it.extension.lowercase()) }
        }

        if (typeFiltered.size == 1) {
            return Result.success(typeFiltered.first())
        }

        // Exact template match: task_<id>.<ext> without additional dots or suffixes
        val exactMatches = (if (typeFiltered.isNotEmpty()) typeFiltered else validCandidates).filter { candidate ->
            val nameWithoutExt = candidate.name.substringBeforeLast('.')
            nameWithoutExt == taskPrefix
        }

        if (exactMatches.size == 1) {
            return Result.success(exactMatches.first())
        }

        // Ambiguous candidates that cannot be reliably distinguished - do NOT randomly pick or use maxByOrNull
        val candidateNames = validCandidates.joinToString(", ") { it.name }
        return Result.failure(
            DownloadError.Generic(
                msg = "Could not reliably determine final output file for task $taskId",
                detail = "Multiple conflicting media files found in task directory: [$candidateNames]"
            )
        )
    }
}
